### ISSUE TITLE
ModuleNotFoundError: No module named 'bottle.ext.websocket'

### ISSUE THREAD

**Issue by HamzaGbada** [Piiii31/Language-directory-finder#1]
I just followed the instructioon from `README.md`, however it does not work and throw the following error:

```python
Traceback (most recent call last):
  File "/home/user/PycharmProjects/Language-directory-finder/main.py", line 4, in <module>
    import eel
  File "/home/user/PycharmProjects/Language-directory-finder/venv/lib/python3.12/site-packages/eel/__init__.py", line 16, in <module>
    import bottle.ext.websocket as wbs
ModuleNotFoundError: No module named 'bottle.ext.websocket'
```

**General information**

- OS: 6.8.9-3-MANJARO 
- Python version: `Python 3.12.3`
- IDEA: Pycharm 2024.1.2
**Steps to reproduce**

    ```bash
    python -m venv .venv
    source .venv/bin/activate   # On Windows, use: .venv\Scripts\activate
    pip install -r requirements.txt
    python main.py
    ```

**Comment by Piiii31** [comment]
---

**Workaround (Outdated)**

Fortunately, `bottle-websocket` can be used and should work similarly. I got mine working with Python 3.12.

You just need to change an import in `__init__.py` in the Eel module.

Find this line:
```python
import bottle.ext.websocket as wbs
```
and replace it with:
```python
import bottle_websocket as wbs
```

Make sure to update the required packages:
```bash
pip install --upgrade bottle-websocket setuptools
```

**Comment by HamzaGbada** [comment]
![image](https://github.com/Piiii31/Language-directory-finder/assets/50714796/7cdfe4f3-e8e7-49ab-aea1-d433b0d89b79)

(**Note:** your answer is generated using chatgpt :) )

**Comment by Piiii31** [comment]
I just formated here is the original: 
https://stackoverflow.com/questions/77232001/python-eel-module-unable-to-use-import-bottle-ext-websocket-as-wbs-modulenotfoun

**Comment by Piiii31** [comment]
its fixed now

**Comment by HamzaGbada** [comment]
I don't think so:
Here is an update if current issue:

```python
Traceback (most recent call last):
  File "/home/bobmarley/PycharmProjects/Language-directory-finder/venv/lib/python3.12/site-packages/eel/__init__.py", line 319, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bobmarley/PycharmProjects/Language-directory-finder/main.py", line 53, in list_directories
    directories = scan_directories(drive, language)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bobmarley/PycharmProjects/Language-directory-finder/main.py", line 38, in scan_directories
    with os.scandir(drive) as entries:
         ^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/dev/nvme0n1p3'
```

I think, it does not recognize my `nvme` drive.
